/*
 * PiEstimator.h
 *
 *  Created on: Oct 8, 2018
 *      Author: arthur
 */

#ifndef SRC_PIESTIMATOR_PIESTIMATOR_H_
#define SRC_PIESTIMATOR_PIESTIMATOR_H_

#include "xparameters.h"
#include "xil_io.h"

#define PIESTIMATOR_MAX_INSTANCES 33
#define PIESTIMATOR_NUM_INSTANCES 10

const u32 piestimator_addr[PIESTIMATOR_MAX_INSTANCES] = {
	XPAR_AXI_PIESTIMATOR_0_BASEADDR,
	XPAR_AXI_PIESTIMATOR_1_BASEADDR,
	XPAR_AXI_PIESTIMATOR_2_BASEADDR,
	XPAR_AXI_PIESTIMATOR_3_BASEADDR,
	XPAR_AXI_PIESTIMATOR_4_BASEADDR,
	XPAR_AXI_PIESTIMATOR_5_BASEADDR,
	XPAR_AXI_PIESTIMATOR_6_BASEADDR,
	XPAR_AXI_PIESTIMATOR_7_BASEADDR,
	XPAR_AXI_PIESTIMATOR_8_BASEADDR,
	XPAR_AXI_PIESTIMATOR_9_BASEADDR,
	XPAR_AXI_PIESTIMATOR_10_BASEADDR,
	XPAR_AXI_PIESTIMATOR_11_BASEADDR,
	XPAR_AXI_PIESTIMATOR_12_BASEADDR,
	XPAR_AXI_PIESTIMATOR_13_BASEADDR,
	XPAR_AXI_PIESTIMATOR_14_BASEADDR,
	XPAR_AXI_PIESTIMATOR_15_BASEADDR,
	XPAR_AXI_PIESTIMATOR_16_BASEADDR,
	XPAR_AXI_PIESTIMATOR_17_BASEADDR,
	XPAR_AXI_PIESTIMATOR_18_BASEADDR,
	XPAR_AXI_PIESTIMATOR_19_BASEADDR,
	XPAR_AXI_PIESTIMATOR_20_BASEADDR,
	XPAR_AXI_PIESTIMATOR_21_BASEADDR,
	XPAR_AXI_PIESTIMATOR_22_BASEADDR,
	XPAR_AXI_PIESTIMATOR_23_BASEADDR,
	XPAR_AXI_PIESTIMATOR_24_BASEADDR,
	XPAR_AXI_PIESTIMATOR_25_BASEADDR,
	XPAR_AXI_PIESTIMATOR_26_BASEADDR,
	XPAR_AXI_PIESTIMATOR_27_BASEADDR,
	XPAR_AXI_PIESTIMATOR_28_BASEADDR,
	XPAR_AXI_PIESTIMATOR_29_BASEADDR,
	XPAR_AXI_PIESTIMATOR_30_BASEADDR,
	XPAR_AXI_PIESTIMATOR_31_BASEADDR,
	XPAR_AXI_PIESTIMATOR_32_BASEADDR
};
#define PIESTIMATOR_REG(inst, reg) ((piestimator_addr[inst]) + (reg<<2))

#define PIESTIMATOR_SET_SEED_REG(inst) PIESTIMATOR_REG(inst, 0)
#define PIESTIMATOR_SEED_REG(inst) PIESTIMATOR_REG(inst, 1)
#define PIESTIMATOR_DONE_REG(inst) PIESTIMATOR_REG(inst, 2)
#define PIESTIMATOR_RESULT_REG(inst) PIESTIMATOR_REG(inst, 3)

#define PIESTIMATOR_CONTROL_ADDR XPAR_AXI_PIESTIMATOR_CONTROL_0_BASEADDR
#define PIESTIMATOR_CONTROL_START_REG (PIESTIMATOR_CONTROL_ADDR)
#define PIESTIMATOR_CONTROL_DURATION_REG (PIESTIMATOR_CONTROL_ADDR+4)



#endif /* SRC_PIESTIMATOR_PIESTIMATOR_H_ */
